name: REPLACE_ME
services: 
  php: 
    container_name: REPLACE_ME_php
    build: 
      dockerfile: ./app/Dockerfile
      context: .
      tags: 
       - "php:8.3-cli"
    image: "php:8.3-cli"
    working_dir: /app
    volumes: 
      - type: bind
        source: ../src
        target: /app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
  mailpit:
    container_name: REPLACE_ME_mailpit
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
